using Academic.Domain.Common;
using Academic.Domain.Enums;
using System;

namespace Academic.Domain.Entities
{
    /// <summary>
    /// Represents a specific test, exam, or assignment conducted in a class/subject.
    /// </summary>
    public class Assessment : BaseEntity
    {
        public string Name { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;

        // Links to the academic context
        public Guid ClassId { get; set; }
        public Guid SubjectId { get; set; }

        // Properties for scoring
        public int MaxScore { get; set; } // The maximum score achievable (e.g., 20, 50, 100)
        public AssessmentType Type { get; set; }

        public DateTime AssessmentDate { get; set; }

        // Navigation Properties (linking to existing entities)
        public Class Class { get; set; } = null!;
        public Subject Subject { get; set; } = null!;

        // Navigation Property to link to the scores generated by this assessment
        //public ICollection<Result> Results { get; set; } = new List<Result>();
    }
}